### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by jarcoal** [GoodCloud/django-zebra#25]
It looks like this project is dead.    I've tried to contact GoodCloud, but they have not responded to any emails / pull requests.

I have a fork [over here](/jarcoal/django-zebra) that has a few small updates and removed some deprecated functionality that I don't anyone is still using.  If anyone is interested I can submit that to PyPi and we can make it the new "master".  If anyone else has a good fork, I'm all for using that instead.

Thoughts?  GoodCloud are you there?

**Comment by skoczen** [comment]
Not quite dead :)

But admittedly slow.  Typically, when pulls have come in, with tests, I've merged them pretty quickly. Life's been pretty crazy for me in the past few months, and GoodCloud's no longer paying the bills, so this has become a free-time-only project competing for a pretty small slice of time. Don't remember seeing any emails, but apologies just the same.

I'm definitely open to someone else picking up the reins and running, as I don't need this code day-to-day, and don't have time to keep it up.  If you're interested in being that person, let me know, and why!

Thanks,
Steven

**Comment by jarcoal** [comment]
Hi Steven,

Thanks for responding.  Sorry about the delay, I've been in the process of launching a new service with the help of django-zebra (thank you!).

Knowing that you're around, I think it makes sense to keep this as the main repo, maybe just add some collaborators to manage pull requests / PyPi releases?

Best,
Jared

**Comment by skoczen** [comment]
Congrats!

Yeah, completely up for adding some collabs.  Are you interested in being one?  Know of others?

To me, the more people we have (responsibly) hacking on the codebase, particularly those who are using it in production, the better!

-S

**Comment by jarcoal** [comment]
Hey, I'm back :)

If you don't mind adding me as a collab on this I will try and help with some of these pull requests.

**Comment by skoczen** [comment]
You got it!  Added you to the team, let me know if you run into any trouble.

Also, you're a Portlander as well?  There should be beers sometime!

-S

**Comment by jarcoal** [comment]
I am!  On that note, a friend and I are organizing a [Django meet-up](http://www.meetup.com/pdxpython/events/132818042/) tomorrow, you should drop by!

**Comment by skoczen** [comment]
Nice!  Am booked later in the evening, but will try to get down for the start!

**Comment by jarcoal** [comment]
Great, look forward to seeing you!
