### ISSUE TITLE
Webhooks broken in Django 1.6

### ISSUE THREAD

**Issue by erikcw** [GoodCloud/django-zebra#30]
Webhooks are throwing exceptions since upgrading to Django 1.6.

According to the [Django Deprecation Timeline](https://docs.djangoproject.com/en/dev/internals/deprecation/) for 1.6, `The attribute HttpRequest.raw_post_data was renamed to HttpRequest.body in 1.4. The backward compatibility will be removed – HttpRequest.raw_post_data will no longer work.`

```
Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "newrelic/hooks/framework_django.py", line 485, in wrapper
    return wrapped(*args, **kwargs)
  File "django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "zebra/views.py", line 67, in webhooks_v2
    event_json = simplejson.loads(request.raw_post_data)

```

Looks like changing `request.raw_post_data` to `request.body` will fix the problem.  Might need to add sniffing for older versions of Django...

**Comment by jarcoal** [comment]
resolved in #31
